plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yuelan.bb338core'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yuelan.bb338core'
        minSdk 24
        targetSdk 35
        versionCode 33803
        versionName '3.3.8-core-rc3'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
    }
}
